version: "3"

services:
  atma-fm:
    build: .

  prometheus:
    image: bitnami/prometheus:2.51.0
    volumes:
      - ./monitor/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
