version: "3"

services:
  atma-fm:
    build:
      context: .
    volumes:
      - .:/app
      - /app/venv
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=development


  prometheus:
    image: bitnami/prometheus:2.51.0
    volumes:
      - ./monitor/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus