# Simplified GitHub Actions workflow
name: Deploy Atma.FM

on:
  push:
    branches:
      - master

jobs:
  deploy: # Changed job name from 'build-and-deploy' to 'deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e # Exit immediately if any command fails
            cd /home/nirvikalpa/atma-fm
            git pull origin master
            
            # Now, instead of pulling a pre-built image, we'll build it
            # using the docker-compose command.
            # We'll use the 'up' command with the '--build' flag.
            
            echo "Building and starting services..."
            # This command will build images that are defined with 'build' and
            # recreate and start all services.
            docker compose -f docker-compose.yaml up -d --build --force-recreate
            
            echo "Deployment successful for commit ${{ github.sha }}!"