name: Deploy Atma.FM

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Web App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Explicitly point to the Dockerfile for the web app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/atma-fm-flask:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to your project directory on the server
            cd /home/nirvikalpa/atma-fm

            # Pull the latest code changes from your master branch
            # This ensures your server has the new docker-compose.prod.yaml file
            git pull origin master

            # --- THIS IS THE CRITICAL CHANGE ---
            # Use BOTH docker-compose files to run the commands.
            # The 'prod' file will override the 'web' service to use the new image.
            
            # 1. Pull the new image for the 'web' service from Docker Hub
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml pull web

            # 2. Restart the 'web' service using the new image
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --no-deps --force-recreate web
            
            echo "Deployment successful!"